### ISSUE TITLE
macOS: cannot use OS-wide Cmd+H, because it's occupied by in-app "Show/hide visual details"

### ISSUE THREAD

**Issue by beetrootpaul** [deepnight/ldtk#960]
There is a macOS shortcut I use many, many times every day on macOS: Cmd+H. It hides the active window. Unfortunately, when in LDtk I cannot use it, because the same shortcut is assigned to "Show/hide visual details", preventing the OS one.

I am aware it might be difficult to support cases like that, because there always might be yet another OS shortcut that someone uses etc. I wonder if it would make sense then (assuming the shortcut customization is a quite big undertake) to for example make it possible to disable certain LDtk shortcuts 🤔

---

LDtk version: 1.3.4
macOS version: Ventura 13.5.2

**Comment by deepnight** [comment]
Fixed in 1.4.0

**Comment by beetrootpaul** [comment]
I'm happy for the change 💛 

Sadly, I am coming back to report two related issues:
1. Right now the `Cmd+H` does nothing. Is it possible LDtk does not pass the shortcut further to the OS? Therefore re-opening this issue here as the change did not solved the inability to to hide the window on macOS.
2. Minor: the shortcut shown in the help sheet still shows cmd/ctrl instead of shift (see screenshot)

<img width="304" alt="screenshot 2023-09-22 at 16 23 40" src="https://github.com/deepnight/ldtk/assets/92947323/e275042d-31ce-480b-9c3c-c98915aa734a">

Note: I can help with debugging on macOS if needed, just let me know 👍
